### PR TITLE
adding timelimit status

### LINKED ISSUE #3: Unknown solver status for timeout
If solution was terminated due to a timelimt, `ROI` terminates with an error

```
Error in make_OP_solution(solution = solution, objval = optimum, status = status,  : 
  unknown solver status code. Please contact the ROI.plugin.cbc maintainer.
```

### PR DESCRIPTION
**Pull request by byapparov**
resolves #3 

depends on https://github.com/dirkschumacher/rcbc/pull/25/

### CODE REVIEW

**Comment by dirkschumacher** [comment]
Great, thanks 👍 . Could you please increase the 4th part of the version number in `rcbc` and this package to `0.1.0.9001` and in the `DESCRIPTION` of this package set the lower bound for `rcbc` to that version in the `imports` field. I.e. `rcbc (>= 0.1.0.9001)`. This ensures that the correct `rcbc` version is used.

**Comment by byapparov** [comment]
@dirkschumacher done. PR against rcbc already has `9001` dev index in DESCRIPTION.

**Comment by byapparov** [comment]
Also, note that `timelimit` status will be treated as success. Which can be acceptable in some cases, but not ideal for everyone.

**Comment by rickyars** [comment]
@byapparov if i wanted to use your patch until this gets merged, how would i do that?

**Comment by dirkschumacher** [comment]
Thanks again. Since there are only two status types (last time I checked), treating `timeout` as `success` seems to be reasonable.

**Comment by dirkschumacher** [comment]
@byapparov thanks a lot for your work! 👍

**Comment by rickyars** [comment]
Trying to debug this, but it doesn't seem to be working. Now when I timeout I get the status "optimal" returned.
```
Result - Stopped on time limit

Objective value:                77.00000000
Lower bound:                    79.000
Gap:                            -0.03
Enumerated nodes:               3820
Total iterations:               176023
Time (CPU seconds):             9.93
Time (Wallclock seconds):       10.01

Total time (CPU seconds):       9.93   (Wallclock seconds):       10.01

Warning message:
In ROI::ROI_solve(op, solver, ...) :
  the control argument "verbosity" is not available in solver 'cbc'
> solver_status(result)
[1] "optimal"
```

**Comment by rickyars** [comment]
Ah, reading the comments and the code, I see that we return "optimal" when the time limit is hit. Are you sure this is the best solution? I would rather be told *not* optimal and then figure out what to do with the solution returned by the model myself.

**Comment by rickyars** [comment]
That said, I *LOVE* that the solution is returned!!! No more converting via `ROI_model` and resolving!!

**Comment by rickyars** [comment]
There are some inconsistencies in the return values and how they are mapped. E.g.,
- `nodelimit` is FAILURE
- `solutionlimit` is SUCCESS
- `abandoned` is FAILURE
- `iterationlimit` is FAILURE
- `timelimit` is SUCCESS

**Comment by dirkschumacher** [comment]
Thanks @rickyars. I will create an issue

**Pull request merged**
